# Generated by Django 4.2.27 on 2026-01-17 08:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("acceptance_criteria", models.JSONField(blank=True, default=list)),
                (
                    "agent_role",
                    models.CharField(
                        choices=[
                            ("PM", "Project Manager"),
                            ("FRONTEND", "Frontend Developer"),
                            ("BACKEND", "Backend Developer"),
                            ("QA", "QA Engineer"),
                            ("DEVOPS", "DevOps Engineer"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "To Do"),
                            ("IN_PROGRESS", "In Progress"),
                            ("IN_REVIEW", "In Review"),
                            ("DONE", "Done"),
                        ],
                        default="TODO",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "Critical"),
                            (2, "High"),
                            (3, "Medium"),
                            (4, "Low"),
                            (5, "Optional"),
                        ],
                        default=3,
                    ),
                ),
                ("dependencies", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
                "ordering": ["priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"], name="tasks_project_fe19a5_idx"
                    ),
                    models.Index(
                        fields=["project", "agent_role"],
                        name="tasks_project_0998e3_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"], name="tasks_status_ec5702_idx"
                    ),
                ],
            },
        ),
    ]
