# Generated by Django 4.2.27 on 2026-01-31 22:14

import apps.tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="acceptance_criteria",
            field=models.JSONField(blank=True, default=apps.tasks.models.empty_list),
        ),
        migrations.AlterField(
            model_name="task",
            name="dependencies",
            field=models.JSONField(blank=True, default=apps.tasks.models.empty_list),
        ),
    ]
