# Generated by Django 4.2.27 on 2026-01-30 08:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("attempts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttemptEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOG", "Log Output"),
                            ("STATUS", "Status Change"),
                            ("PROGRESS", "Progress Update"),
                            ("ERROR", "Error Message"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "attempt_events",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AttemptGateResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gate_type",
                    models.CharField(
                        choices=[
                            ("TEST", "Test Execution"),
                            ("LINT", "Code Linting"),
                            ("BUILD", "Build Verification"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        max_length=50,
                    ),
                ),
                ("output", models.TextField(blank=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "attempt_gate_results",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="attempt",
            name="diff",
            field=models.TextField(blank=True, help_text="Git diff output"),
        ),
        migrations.AddField(
            model_name="attempt",
            name="git_branch",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="attempt",
            name="logs",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="attempt",
            name="worktree_path",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("QUEUED", "Queued"),
                    ("RUNNING", "Running"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(
                fields=["task", "-created_at"], name="attempts_task_id_58c57c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(
                fields=["status", "-created_at"], name="attempts_status_6e6e53_idx"
            ),
        ),
        migrations.AddField(
            model_name="attemptgateresult",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gate_results",
                to="attempts.attempt",
            ),
        ),
        migrations.AddField(
            model_name="attemptevent",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="attempts.attempt",
            ),
        ),
        migrations.AddIndex(
            model_name="attemptgateresult",
            index=models.Index(
                fields=["attempt", "gate_type"], name="attempt_gat_attempt_dcf6e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attemptevent",
            index=models.Index(
                fields=["attempt", "timestamp"], name="attempt_eve_attempt_7a53d5_idx"
            ),
        ),
    ]
