# Generated by Django 4.2.27 on 2026-01-30 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WritableRoot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "path",
                    models.CharField(
                        help_text="Absolute path on the local machine", max_length=1024
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writable_roots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "writable_roots",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PMDecomposition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "requirements",
                    models.TextField(help_text="Original user requirements"),
                ),
                (
                    "generated_tasks",
                    models.JSONField(
                        default=list,
                        help_text="List of task dicts generated by PM agent",
                    ),
                ),
                (
                    "tasks_created",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of created task IDs after approval",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        default="gemini-2.5-flash",
                        help_text="LLM model used for decomposition",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pm_decompositions",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "pm_decompositions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("READ", "Read"),
                            ("WRITE", "Write"),
                            ("DELETE", "Delete"),
                            ("EXECUTE", "Execute"),
                            ("GIT_COMMIT", "Git Commit"),
                            ("GIT_MERGE", "Git Merge"),
                        ],
                        max_length=50,
                    ),
                ),
                ("path", models.CharField(max_length=1024)),
                (
                    "result",
                    models.CharField(
                        choices=[("ALLOWED", "Allowed"), ("DENIED", "Denied")],
                        default="ALLOWED",
                        max_length=50,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="audit_logs_user_id_6193b2_idx",
                    ),
                    models.Index(
                        fields=["result", "-created_at"],
                        name="audit_logs_result_a8228f_idx",
                    ),
                ],
            },
        ),
    ]
