from django.db import models
from django.conf import settings
import uuid


class WritableRoot(models.Model):
    """User-approved folders where LDA can write/delete files."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='writable_roots',
        null=True,
        blank=True
    )
    name = models.CharField(max_length=255)
    path = models.CharField(max_length=1024, help_text="Absolute path on the local machine")
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        db_table = 'writable_roots'

    def __str__(self):
        return f"{self.name} ({self.path})"


class AuditLog(models.Model):
    """Audit log for all filesystem operations by LDA."""
    OPERATION_CHOICES = [
        ('READ', 'Read'),
        ('WRITE', 'Write'),
        ('DELETE', 'Delete'),
        ('EXECUTE', 'Execute'),
        ('GIT_COMMIT', 'Git Commit'),
        ('GIT_MERGE', 'Git Merge'),
    ]

    RESULT_CHOICES = [
        ('ALLOWED', 'Allowed'),
        ('DENIED', 'Denied'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name='audit_logs'
    )
    task = models.ForeignKey(
        'tasks.Task',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    action = models.CharField(max_length=50, choices=OPERATION_CHOICES)
    path = models.CharField(max_length=1024)
    result = models.CharField(max_length=50, choices=RESULT_CHOICES, default='ALLOWED')
    details = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        db_table = 'audit_logs'
        indexes = [
            models.Index(fields=['user', '-created_at']),
            models.Index(fields=['result', '-created_at']),
        ]

    def __str__(self):
        return f"[{self.result}] {self.action} on {self.path}"


class PMDecomposition(models.Model):
    """Record of PM Agent task decomposition."""
    STATUS_CHOICES = [
        ('PENDING', 'Pending Approval'),
        ('APPROVED', 'Approved'),
        ('REJECTED', 'Rejected'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(
        'projects.Project',
        on_delete=models.CASCADE,
        related_name='pm_decompositions'
    )
    requirements = models.TextField(help_text="Original user requirements")
    generated_tasks = models.JSONField(
        default=list,
        help_text="List of task dicts generated by PM agent"
    )
    tasks_created = models.JSONField(
        default=list,
        blank=True,
        help_text="List of created task IDs after approval"
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='PENDING'
    )
    model_used = models.CharField(
        max_length=100,
        default='gemini-2.5-flash',
        help_text="LLM model used for decomposition"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        db_table = 'pm_decompositions'

    def __str__(self):
        return f"PM Decomposition for {self.project.name} [{self.status}]"

    @property
    def task_count(self):
        return len(self.generated_tasks)

